#!/usr/bin/env python3
"""Generate mod/window.h: a 256-entry Q15 Hann window (the device has no libm)."""
import math
import os

N = 256
rows = ["%d" % round(32767 * math.sin(math.pi * (i + 0.5) / N) ** 2) for i in range(N)]
out = ["/* SPDX-License-Identifier: GPL-2.0-or-later */",
       "/* Generated by tools/gen_window.py: do not edit. Hann window, Q15, %d entries. */" % N,
       "#define GR_WIN_N %d" % N,
       "static const short gr_win[GR_WIN_N] = {"]
for i in range(0, N, 12):
    out.append("    " + ", ".join(rows[i:i + 12]) + ",")
out.append("};")
path = os.path.join(os.path.dirname(os.path.abspath(__file__)), "..", "mod", "window.h")
with open(path, "w") as f:
    f.write("\n".join(out) + "\n")
